# Run this to download kubeconfig from remote
---
- hosts: kubernetes

  tasks:
    - name: Get kubeconfig to /tmp/kubeconfig
      shell: microk8s config > /tmp/kubeconfig

    - name: Download kubeconfig into ~/.kube folder
      fetch:
        src: /tmp/kubeconfig
        dest: ~/.kube/microk8s
        # Replace the file, do not append
        flat: true

    - name: Replace IP with `kubernetes` in the kubeconfig
      shell: sed -i 's/192\.[^.]*\.[^.]*\.[0-9]*/kubernetes/g' ~/.kube/microk8s
      delegate_to: localhost

    - name: Delete kubeconfig from /tmp/kubeconfig
      shell: rm /tmp/kubeconfig
