---
- name: Stop microk8s snap service
  hosts: kubernetes
  become: true

  tasks:
    - name: Snap stop microk8s
      command: snap stop microk8s

    - name: microk8s stop
      command: microk8s stop
