---
- hosts: localhost
  become: true
  vars_files:
    - ../vars.yml

  tasks:
    - name: Add openvpn3 repo
      yum_repository:
        name: copr:copr.fedorainfracloud.org:dsommers:openvpn3
        description: OpenVPN3 repo by dsommers
        baseurl: https://download.copr.fedorainfracloud.org/results/dsommers/openvpn3/fedora-$releasever-$basearch/
        gpgkey: https://download.copr.fedorainfracloud.org/results/dsommers/openvpn3/pubkey.gpg

    - name: Add docker-ce repo
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        gpgkey: https://download.docker.com/linux/fedora/gpg

    - name: Update DNF cache
      dnf:
        update_cache: true
        state: latest

    - name: Ensure C development tools
      dnf:
        name:
          - git
          - '@C Development Tools and Libraries'
        state: present

    - name: Ensure mandatory tool installed
      dnf:
        state: present
        name:
          - bat
          - fzf
          - kitty
          - neovim
          - postgresql
          - postgresql-server
          - rcm
          - redis
          - the_silver_searcher
          - tmux
          - vips
          - zsh

    - name: Ensure docker installed
      dnf:
        state: present
        name:
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin

    - name: Ensure tt (typing test) is available. Absolutely required!
      ansible.builtin.get_url:
        url: https://github.com/lemnos/tt/releases/download/v0.4.2/tt-linux
        dest: /usr/local/bin/tt
        mode: '0755'

    - name: Uninstall useless tools
      dnf:
        state: absent
        autoremove: true
        name:
          - '@Container management'
          - cheese
          - gnome-boxes
          - gnome-maps
          - gnome-photos
          - gnome-tour
          - gnome-weather
          - mediawriter
          - rhythmbox
          - totem

    - name: Clone karunsiri/dotfiles to ~/.dotfiles
      git:
        repo: https://github.com/karunsiri/dotfiles.git
        dest: /home/karun/.dotfiles
      failed_when: false
      become: true
      become_user: "{{ username }}"

    - name: Whole System Upgrade
      dnf:
        name: '*'
        state: latest

    - name: Detect ZSH path
      shell: which zsh
      register: zsh_path

    - name: Detect user id
      shell: id -u
      register: user_id
      become: true
      become_user: "{{ username }}"

    - name: Change shell to ZSH
      lineinfile:
        path: /etc/passwd
        regexp: '^{{ username }}'
        line: "{{ username }}:x:{{ user_id.stdout }}:{{ user_id.stdout }}:{{ username }}:/home/{{ username }}:{{ zsh_path.stdout }}"

    - name: Sync dotfiles
      become: true
      become_user: "{{ username }}"
      shell: |
        RCRC=$HOME/.dotfiles/rcrc
        rcup
      args:
        executable: "{{ zsh_path.stdout }}"

    - name: Ensure user fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        state: directory
      become: true
      become_user: "{{ username }}"

    - name: Check if 'FiraCode Nerd Font' exists
      shell: |
        ls {{ lookup('env', 'HOME') }}/.local/share/fonts/FiraCodeNerdFont*
      register: fc_font
      ignore_errors: true

    - name: Download 'FiraCode Nerd Font' font if not exist
      when: fc_font is failed
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/"
        remote_src: yes
      become: true
      become_user: "{{ username }}"

    - name: Check if 'VictorMono' exists
      shell: |
        ls {{ lookup('env', 'HOME') }}/.local/share/fonts/VictorMono
      register: victor_font
      ignore_errors: true

    - name: Download 'VictorMono' font if not exist
      when: victor_font is failed
      unarchive:
        src: https://rubjo.github.io/victor-mono/VictorMonoAll.zip
        dest: /tmp
        include:
          - 'TTF/VictorMono-MediumOblique.ttf'
          - 'TTF/VictorMono-BoldOblique.ttf'
        remote_src: yes
      become: true
      become_user: "{{ username }}"

    - name: Ensure 'VictorMono' font is installed
      when: victor_font is failed
      shell: |
        cp /tmp/TTF/* {{ lookup('env', 'HOME') }}/.local/share/fonts
      become: true
      become_user: "{{ username }}"
