# Run this to download kubeconfig from remote
---
- hosts: kubernetes
  vars:
    api_port: 6443
    ddns_port: 23991

  tasks:
    - name: Get kubeconfig to /tmp/kubeconfig
      become: true
      shell: k0s kubeconfig admin > /tmp/kubeconfig

    - name: Download kubeconfig into ~/.kube folder
      fetch:
        src: /tmp/kubeconfig
        dest: ~/.kube/k0s
        # Replace the file, do not append
        flat: true

    - name: Replace API port
      shell: sed -i 's/{{ api_port }}/{{ ddns_port }}/g' ~/.kube/k0s
      delegate_to: localhost

    - name: Delete kubeconfig from /tmp/kubeconfig
      become: true
      shell: rm /tmp/kubeconfig
